/** Plain-English definitions. `lesson` is the lesson id where the idea is taught. */
export interface Term { term: string; def: string; lesson: string }

export const glossary: Term[] = [
  { term: 'Closure', def: 'A function that remembers the variables from where it was created, even after that place has finished running.', lesson: 'closures' },
  { term: 'Scope', def: 'The part of the code where a variable can be seen. Lookups start in the innermost scope and step outward.', lesson: 'closures' },
  { term: 'Lexical scope', def: 'Scope decided by where code is written, not where it runs.', lesson: 'closures' },
  { term: 'this', def: 'A value set each time a function is called, usually the object left of the dot. Arrow functions have no this of their own.', lesson: 'this-prototypes' },
  { term: 'Prototype', def: 'A hidden link from an object to another object that it borrows properties from when it does not have them itself.', lesson: 'this-prototypes' },
  { term: 'Constructor', def: 'A function used with new to create objects of one kind.', lesson: 'this-prototypes' },
  { term: 'Callback', def: 'A function you hand to someone else to call later.', lesson: 'promises' },
  { term: 'Promise', def: 'An object standing in for a value that is not ready yet. It is pending, then fulfilled or rejected, exactly once.', lesson: 'promises' },
  { term: 'Microtask', def: 'A small job (like a promise callback) that runs as soon as the current code ends, before the next timer.', lesson: 'event-loop' },
  { term: 'Event loop', def: 'The rule that picks what JavaScript runs next: one task, then all microtasks, then maybe a repaint.', lesson: 'event-loop' },
  { term: 'async / await', def: 'Syntax for writing promise code top to bottom. await pauses only that function until the promise settles.', lesson: 'async-await' },
  { term: 'AbortController', def: 'An object that lets you tell an operation (like a fetch) to stop, through its signal.', lesson: 'async-await' },
  { term: 'Debounce', def: 'Run a function only after the events have stopped for a while.', lesson: 'event-loop' },
  { term: 'Throttle', def: 'Run a function at most once per time window while events keep coming.', lesson: 'event-loop' },
  { term: 'Iterator', def: 'Something with a next() method that returns { value, done } until it is finished.', lesson: 'iterators' },
  { term: 'Generator', def: 'A function (function*) that can pause at each yield and resume later, producing values lazily.', lesson: 'iterators' },
  { term: 'Pure function', def: 'A function whose output depends only on its inputs and which has no side effects.', lesson: 'functional' },
  { term: 'Higher-order function', def: 'A function that takes or returns other functions.', lesson: 'functional' },
  { term: 'Currying', def: 'Turning f(a, b, c) into f(a)(b)(c): one argument per call.', lesson: 'functional' },
  { term: 'Immutability', def: 'Never changing data in place; build a new copy instead. React and memoised selectors rely on it.', lesson: 'objects' },
  { term: 'Shallow copy', def: 'A copy of the top level only; nested objects are still shared with the original.', lesson: 'objects' },
  { term: 'Reference', def: 'A link to an object. Copying a variable holding an object copies the link, not the object.', lesson: 'objects' },
  { term: 'Generic', def: 'A type with a slot (like T) that is filled in by whoever uses it.', lesson: 'ts-generics' },
  { term: 'Type narrowing', def: 'Checks in your code (typeof, ===, in) that turn a wide type into a more specific one inside a branch.', lesson: 'ts-generics' },
  { term: 'Conditional type', def: 'An if statement for types: A extends B ? X : Y.', lesson: 'ts-generics' },
  { term: 'Mapped type', def: 'A type that loops over the keys of another type to build a new one: { [K in keyof T]: … }.', lesson: 'ts-type-level' },
  { term: 'Template literal type', def: 'A type built from string pieces, which can also take strings apart with infer.', lesson: 'ts-type-level' },
  { term: 'Type predicate', def: 'A return type like x is string that promises the compiler what a true result means.', lesson: 'ts-real-world' },
  { term: 'JSX', def: 'Markup-like syntax that compiles to function calls returning React elements.', lesson: 'react-rendering' },
  { term: 'Props', def: 'The read-only inputs a component receives from its parent.', lesson: 'react-rendering' },
  { term: 'Key (React)', def: 'An identity for list items so React knows which item is which between renders.', lesson: 'react-rendering' },
  { term: 'State', def: 'Data a component remembers between renders; changing it makes React redraw.', lesson: 'react-state' },
  { term: 'Controlled input', def: 'A form field whose value lives in React state and flows back through onChange.', lesson: 'react-state' },
  { term: 'Lifting state up', def: 'Moving state to the closest common parent so siblings can share it.', lesson: 'react-state' },
  { term: 'Effect', def: 'Code that runs after rendering to sync with the outside world (timers, events, network).', lesson: 'react-effects' },
  { term: 'Cleanup', def: 'The function an effect returns; it undoes what the effect set up.', lesson: 'react-effects' },
  { term: 'Dependency array', def: 'The list of values an effect reads; React re-runs the effect when one changes.', lesson: 'react-effects' },
  { term: 'Stale closure', def: 'A function still using an old value from an earlier render.', lesson: 'react-effects' },
  { term: 'Custom hook', def: 'A function starting with use that calls other hooks, to reuse stateful logic.', lesson: 'react-hooks' },
  { term: 'Ref', def: 'A mutable box that survives renders and does not cause a render when changed.', lesson: 'react-hooks' },
  { term: 'Memoization', def: 'Remembering the result of a calculation so it is not repeated when the inputs are the same.', lesson: 'react-performance' },
  { term: 'Virtualisation', def: 'Rendering only the rows that are visible instead of all of them.', lesson: 'react-performance' },
  { term: 'Context', def: 'A way to share a value with many distant components without passing props through every level.', lesson: 'react-architecture' },
  { term: 'Reducer', def: 'A pure function (state, action) → next state, used to keep update rules in one place.', lesson: 'react-architecture' },
  { term: 'Error boundary', def: 'A component that catches rendering errors in its children and shows a fallback.', lesson: 'react-architecture' },
  { term: 'Compound component', def: 'A set of small components (Tabs, Tabs.List, …) that share state through context.', lesson: 'react-composition' },
  { term: 'ARIA', def: 'Attributes that describe roles and states of custom widgets to assistive technology.', lesson: 'react-composition' },
  { term: 'Roving tabindex', def: 'One item in a widget has tabindex 0 and arrow keys move it, so the widget is a single Tab stop.', lesson: 'react-composition' },
  { term: 'Coalescing', def: 'Keeping only the latest value per key so a fast feed produces far fewer updates.', lesson: 'prod-firehose' },
  { term: 'INP', def: 'Interaction to Next Paint: how long the page takes to respond after a tap or keypress.', lesson: 'prod-firehose' },
  { term: 'Cursor pagination', def: 'Loading the next page by saying "after this item" rather than "page 40", which is stable when data changes.', lesson: 'prod-large-data' },
  { term: 'Time slicing', def: 'Splitting a long job into short chunks with breaks so the page stays responsive.', lesson: 'prod-large-data' },
  { term: 'Backoff with jitter', def: 'Waiting longer after each failed retry, with a random amount so clients do not retry together.', lesson: 'prod-resilience' },
  { term: 'Half-open connection', def: 'A connection that has silently died without any close event.', lesson: 'prod-resilience' },
  { term: 'Sequence number', def: 'A counter on each message that lets a client spot duplicates, gaps and wrong order.', lesson: 'prod-resilience' },
  { term: 'Idempotency key', def: 'A unique id for one logical action so that repeating the request returns the original result.', lesson: 'prod-bet-placement' },
  { term: 'State machine', def: 'A model with explicit states and allowed transitions, so illegal moves are impossible.', lesson: 'prod-bet-placement' },
  { term: 'Memory leak', def: 'Memory that is still reachable but no longer needed, so it is never freed.', lesson: 'prod-memory' },
  { term: 'LRU cache', def: 'A cache that evicts the least recently used entry when it is full.', lesson: 'prod-memory' },
  { term: 'Web Worker', def: 'A separate thread for heavy JavaScript work, talked to with messages.', lesson: 'prod-workers' },
  { term: 'Structured clone', def: 'The algorithm that copies data when you postMessage it.', lesson: 'prod-workers' },
  { term: 'BroadcastChannel', def: 'A way for tabs of the same site to send messages to each other.', lesson: 'prod-multi-tab' },
  { term: 'Last-writer-wins', def: 'A conflict rule: the change with the highest version wins, so every tab converges.', lesson: 'prod-multi-tab' },
  { term: 'Leader election', def: 'Choosing one tab (for example the lowest alive id) to do a job once for everyone.', lesson: 'prod-multi-tab' },
  { term: 'Hash map', def: 'A structure that finds a value by its key in constant time on average (Map in JavaScript).', lesson: 'interview-ds' },
  { term: 'Trie', def: 'A tree with one node per character so words sharing a prefix share nodes.', lesson: 'interview-ds' },
  { term: 'Big-O', def: 'A way to describe how the cost of code grows with the size of its input.', lesson: 'interview-ds' },
  { term: 'Escaping', def: 'Converting special characters so text is treated as data, not as code, in HTML or URLs.', lesson: 'interview-frontend' },
  { term: 'Event bubbling', def: 'After an event hits its target, it travels back up through the parent elements, so a listener higher up can see it.', lesson: 'web-dom' },
  { term: 'Event capturing', def: 'The first half of an event\'s trip: from the document down to the target. Listeners opt in with { capture: true }.', lesson: 'web-dom' },
  { term: 'Event delegation', def: 'One listener on a parent that handles events from many children, using event.target.closest(selector) to find which child it was.', lesson: 'web-dom' },
  { term: 'Layout thrashing', def: 'Mixing DOM writes and layout reads in a loop so the browser has to recalculate layout again and again.', lesson: 'web-dom' },
  { term: 'IntersectionObserver', def: 'A browser API that tells you when an element enters or leaves the viewport, without scroll listeners.', lesson: 'web-dom' },
  { term: 'Compositing', def: 'The last rendering step: stacking painted layers on the GPU. transform and opacity changes only need this step.', lesson: 'web-dom' },
  { term: 'ETag', def: 'A fingerprint of a response. The browser sends it back in If-None-Match so the server can answer 304 Not Modified instead of re-sending the body.', lesson: 'web-network' },
  { term: 'Cache-Control', def: 'A response header that says how long and by whom a response may be reused (max-age, no-cache, no-store, immutable…).', lesson: 'web-network' },
  { term: 'Stale-while-revalidate', def: 'Serve the cached value immediately, even if it is a bit old, and refresh it once in the background.', lesson: 'web-network' },
  { term: 'CORS', def: 'The browser rule that stops a page reading responses from another origin unless that server opts in with Access-Control headers.', lesson: 'web-network' },
  { term: 'Preflight', def: 'An OPTIONS request the browser sends first to ask a cross-origin server whether the real request is allowed.', lesson: 'web-network' },
  { term: 'AbortController', def: 'An object whose signal you pass to fetch (and listeners); calling abort() cancels them.', lesson: 'web-network' },
  { term: 'Core Web Vitals', def: 'Google\'s three user-experience metrics: LCP (loading), INP (responsiveness) and CLS (visual stability).', lesson: 'web-perf' },
  { term: 'LCP', def: 'Largest Contentful Paint: when the biggest element in the viewport finished rendering. Good is 2.5 seconds or less.', lesson: 'web-perf' },
  { term: 'INP', def: 'Interaction to Next Paint: how long the slowest typical tap, click or key press takes to show a visible response. Good is 200 ms or less.', lesson: 'web-perf' },
  { term: 'CLS', def: 'Cumulative Layout Shift: a score for how much visible content jumped around unexpectedly. Good is 0.1 or less.', lesson: 'web-perf' },
  { term: 'Long task', def: 'A main-thread task over 50 ms. Anything the user does while it runs has to wait.', lesson: 'web-perf' },
  { term: 'Percentile', def: 'The value that a given share of samples are at or below. p75 means three out of four samples were this good or better.', lesson: 'web-perf' },
  { term: 'RUM', def: 'Real user monitoring: measuring performance in your actual users\' browsers instead of one test machine.', lesson: 'web-perf' },
  { term: 'Performance budget', def: 'A limit (for example, 170 KB of JavaScript) that a build or CI check enforces so pages do not creep heavier.', lesson: 'web-perf' },
  { term: 'Cursor pagination', def: 'Paging by pointing at the last item you saw instead of a page number, so inserted items do not cause repeats or gaps.', lesson: 'sys-design' },
  { term: 'Optimistic update', def: 'Showing the result of an action right away and rolling it back if the server says no.', lesson: 'sys-design' },
  { term: 'Debounce', def: 'Waiting for a pause in events (like typing) before acting, so a burst causes one action.', lesson: 'sys-design' },
  { term: 'Outbox', def: 'A local queue of things to send (such as chat messages) that retries until they succeed or are marked failed.', lesson: 'sys-design' },
  { term: 'Idempotency key', def: 'An id sent with a request so that repeating it is safe: the server treats the repeat as the same request.', lesson: 'sys-design' },
  { term: 'Big-O', def: 'A way to describe how the work grows as the input grows, ignoring constants: O(1) stays flat, O(n) grows in step, O(n²) grows with the square.', lesson: 'ds-arrays' },
  { term: 'Amortised cost', def: 'The average cost per operation over a long run: an occasional expensive step (like resizing an array) is paid for by many cheap ones.', lesson: 'ds-arrays' },
  { term: 'Binary search', def: 'Finding an item in sorted data by checking the middle and discarding the half that cannot contain it. O(log n).', lesson: 'ds-arrays' },
  { term: 'Hash function', def: 'A function that turns a key into a number, which a hash table reduces to a bucket index. The same key must always give the same number.', lesson: 'ds-hash-tables' },
  { term: 'Collision', def: 'Two different keys landing in the same bucket of a hash table. Chaining keeps a short list in each bucket.', lesson: 'ds-hash-tables' },
  { term: 'Load factor', def: 'Entries divided by buckets in a hash table. When it passes a limit (about 0.75) the table doubles its buckets and rehashes.', lesson: 'ds-hash-tables' },
  { term: 'Stack', def: 'A last-in, first-out collection: you add and remove at the top only. push and pop are O(1).', lesson: 'ds-stacks-queues' },
  { term: 'Queue', def: 'A first-in, first-out collection: add at the back, remove from the front.', lesson: 'ds-stacks-queues' },
  { term: 'Ring buffer', def: 'A fixed-size array whose read and write positions wrap around, so it remembers the last N items with no shifting.', lesson: 'ds-stacks-queues' },
  { term: 'Monotonic stack', def: 'A stack kept in sorted order by discarding items that can never be the answer, used for "next greater" style problems in O(n).', lesson: 'ds-stacks-queues' },
  { term: 'Linked list', def: 'Items stored in separate nodes that each point at the next one. Inserting or removing is O(1) once you hold the node; reaching item k is O(k).', lesson: 'ds-linked-lists' },
  { term: 'Sentinel node', def: 'A dummy node placed at the start (and sometimes end) of a list so the first and last real nodes need no special cases.', lesson: 'ds-linked-lists' },
  { term: 'Fast and slow pointers', def: 'Two pointers moving at different speeds along a list, used to find the middle or detect a cycle with O(1) memory.', lesson: 'ds-linked-lists' },
  { term: 'Binary search tree', def: 'A binary tree where everything in a node\'s left subtree is smaller and everything in its right subtree is larger, so search is O(height).', lesson: 'ds-trees' },
  { term: 'Tree traversal', def: 'Visiting every node: depth-first (pre-, in- or post-order) goes deep first; breadth-first (level-order) goes row by row with a queue.', lesson: 'ds-trees' },
  { term: 'Heap', def: 'A complete binary tree stored in an array where every parent is at most (min-heap) or at least (max-heap) its children. push and pop are O(log n).', lesson: 'ds-heaps' },
  { term: 'Priority queue', def: 'A collection that always hands you the most important item next. A heap is the usual implementation.', lesson: 'ds-heaps' },
  { term: 'Adjacency list', def: 'A graph stored as a map from each node to the list of its neighbours. Uses O(V + E) memory.', lesson: 'ds-graphs' },
  { term: 'Breadth-first search', def: 'Exploring a graph in rings of increasing distance using a queue; it finds shortest paths in unweighted graphs.', lesson: 'ds-graphs' },
  { term: 'Topological sort', def: 'An ordering of a directed acyclic graph where every edge points forward, such as a valid order for tasks with prerequisites.', lesson: 'ds-graphs' },
  { term: 'Dijkstra', def: 'Shortest paths in a graph with non-negative edge weights: always expand the closest unexplored node, using a min-heap.', lesson: 'ds-graphs' },
  { term: 'Union-find', def: 'A structure that tracks which items are connected as sets merge: find climbs to a set\'s root, union joins two roots. Nearly O(1) with path compression.', lesson: 'ds-specialist' },
  { term: 'Prefix sum', def: 'A running total stored so any range sum is one subtraction: sum(l..r) = prefix[r + 1] - prefix[l].', lesson: 'ds-specialist' },
  { term: 'Fenwick tree', def: 'A compact structure for prefix sums that also allows point updates, both in O(log n), using the lowest set bit of an index.', lesson: 'ds-specialist' },
  { term: 'Base case', def: 'The input of a recursive function that is answered directly, without another call. Without one, the recursion never stops.', lesson: 'algo-recursion' },
  { term: 'Call stack', def: 'The record of function calls that are waiting for the calls they made. Very deep recursion overflows it.', lesson: 'algo-recursion' },
  { term: 'Divide and conquer', def: 'Split a problem in half, solve each half recursively, then combine the answers. Merge sort and fast exponentiation are examples.', lesson: 'algo-recursion' },
  { term: 'Memoisation', def: 'Remembering the answer to each subproblem the first time you solve it, so recursion never repeats work.', lesson: 'algo-recursion' },
  { term: 'Two pointers', def: 'Two indexes that move towards each other (or in step) so a nested loop becomes a single pass.', lesson: 'algo-windows' },
  { term: 'Sliding window', def: 'A range [left, right] over an array or string that grows on the right and shrinks on the left, tracking the best valid range in one pass.', lesson: 'algo-windows' },
  { term: 'Quickselect', def: 'Finding the k-th smallest item by partitioning around a pivot and keeping only the side that holds it. O(n) on average.', lesson: 'algo-sorting' },
  { term: 'Binary search on the answer', def: 'Binary searching the candidate answers themselves when a yes/no test on a candidate flips from no to yes only once.', lesson: 'algo-sorting' },
  { term: 'Backtracking', def: 'Building an answer one choice at a time and undoing each choice afterwards: choose, explore, un-choose.', lesson: 'algo-backtracking' },
  { term: 'Pruning', def: 'Abandoning a partial answer as soon as it cannot lead to a valid solution, which skips everything below it.', lesson: 'algo-backtracking' },
  { term: 'Dynamic programming', def: 'Solving a problem by solving its overlapping subproblems once each and combining the stored answers, top-down with a memo or bottom-up with a table.', lesson: 'algo-dp-basics' },
  { term: 'Overlapping subproblems', def: 'When a recursion asks for the same smaller answers again and again. The signal that memoisation or DP will help.', lesson: 'algo-dp-basics' },
  { term: 'DP state', def: 'The precise meaning of a table entry such as dp[i]. Getting this definition right is the key step of any DP solution.', lesson: 'algo-dp-basics' },
  { term: 'Knapsack', def: 'Choosing items, each with a weight and a value, to maximise value within a capacity. In the 0/1 version each item is used at most once.', lesson: 'algo-dp-tables' },
  { term: 'Edit distance', def: 'The fewest single-letter insertions, deletions and replacements that turn one string into another.', lesson: 'algo-dp-tables' },
  { term: 'Greedy algorithm', def: 'Taking the best-looking choice at every step and never reconsidering. Correct only when that local choice provably cannot hurt.', lesson: 'algo-greedy' },
  { term: 'Exchange argument', def: 'A proof technique for greedy algorithms: show any optimal solution can be changed to use the greedy choice without getting worse.', lesson: 'algo-greedy' },
  { term: 'Sweep line', def: 'Processing events (such as interval starts and ends) in time order while tracking a running count.', lesson: 'algo-greedy' },
  { term: 'Unit test', def: 'A small, fast test of one function or component in isolation. Most of a suite should be unit tests.', lesson: 'test-first-tests' },
  { term: 'Arrange, Act, Assert', def: 'The shape of a test: set things up, do the one thing under test, then check the outcome.', lesson: 'test-first-tests' },
  { term: 'Matcher', def: 'A method like toBe or toEqual that compares the value you got with the one you expected.', lesson: 'test-first-tests' },
  { term: 'Mutant', def: 'A copy of the code with a deliberate small bug. A good test suite fails for every mutant.', lesson: 'test-first-tests' },
  { term: 'Equivalence class', def: 'A group of inputs the code should treat the same way. Test one or two from each group.', lesson: 'test-cases-edges' },
  { term: 'Boundary value', def: 'An input at the edge of a rule, such as 49.99 and 50 when 50 is the limit. Bugs cluster here.', lesson: 'test-cases-edges' },
  { term: 'Table-driven test', def: 'One test body run over a table of inputs and expected outputs, so each case is one short row.', lesson: 'test-cases-edges' },
  { term: 'Test double', def: 'A stand-in for a real collaborator in a test: dummy, stub, spy, mock or fake.', lesson: 'test-doubles' },
  { term: 'Stub', def: 'A test double that returns canned answers so the code under test meets the situation you want.', lesson: 'test-doubles' },
  { term: 'Spy', def: 'A test double that records how it was called, so a test can check the calls afterwards.', lesson: 'test-doubles' },
  { term: 'Fake', def: 'A simplified but working implementation used in tests, such as an in-memory repository.', lesson: 'test-doubles' },
  { term: 'Dependency injection', def: 'Passing a collaborator (clock, api, random) into code instead of reaching for a global, so tests can swap it.', lesson: 'test-doubles' },
  { term: 'Seam', def: 'A place where behaviour can be swapped without editing the code, usually a parameter.', lesson: 'test-doubles' },
  { term: 'Fake timers', def: 'A pretend clock a test controls, so timeouts fire when the test says and nothing really waits.', lesson: 'test-async-time' },
  { term: 'Backoff', def: 'Waiting longer after each failed attempt, for example 100, 200, 400 milliseconds.', lesson: 'test-async-time' },
  { term: 'Testing Library', def: 'A way of testing UI by finding elements the way users do (by role, label, text) and acting like a user.', lesson: 'test-react-rtl' },
  { term: 'Accessible name', def: 'The text assistive technology announces for an element, used by getByRole to find it.', lesson: 'test-react-rtl' },
  { term: 'Test-driven development', def: 'Write a failing test, make it pass with the simplest code, then refactor. Repeat in tiny steps.', lesson: 'test-tdd-testability' },
  { term: 'Functional core, imperative shell', def: 'Keep decisions in pure functions and wrap them in a thin layer that talks to the outside world.', lesson: 'test-tdd-testability' },
  { term: 'Flaky test', def: 'A test that sometimes passes and sometimes fails with no code change, usually from uncontrolled time, randomness or shared state.', lesson: 'test-quality' },
  { term: 'Brittle test', def: 'A test that breaks when you refactor without changing behaviour, because it checks internals.', lesson: 'test-quality' },
  { term: 'Mutation testing', def: 'Changing the code slightly and checking that some test fails. Surviving mutants show gaps in the tests.', lesson: 'test-quality' },
  { term: 'Code coverage', def: 'Which lines ran during the tests. It does not show that anything was checked.', lesson: 'test-quality' },
  { term: 'Factory function', def: 'A function that returns a ready-made object, so callers ask for what they need and one place decides how it is built.', lesson: 'pat-factories-builders' },
  { term: 'Registry', def: 'A lookup table (usually a Map) of named makers or services, so new kinds can be added without editing the code that uses them.', lesson: 'pat-factories-builders' },
  { term: 'Builder', def: 'An object that collects settings step by step and creates the final result at the end. An immutable builder returns a new builder from each step.', lesson: 'pat-factories-builders' },
  { term: 'Singleton', def: 'One shared instance. Fine when passed in; harmful as a hidden global that any code can reach.', lesson: 'pat-factories-builders' },
  { term: 'Object pool', def: 'A set of reusable expensive objects that you acquire and release, with a cap on how many exist.', lesson: 'pat-factories-builders' },
  { term: 'Strategy', def: 'A swappable way of doing one step, in JavaScript usually just a function passed in or looked up by name.', lesson: 'pat-strategy-state' },
  { term: 'State pattern', def: 'One explicit status plus a table of allowed transitions, instead of several booleans that allow nonsense combinations.', lesson: 'pat-strategy-state' },
  { term: 'Observer', def: 'A subject keeps a list of listener functions and notifies them when it changes, without knowing who they are.', lesson: 'pat-observer' },
  { term: 'Pub/sub', def: 'A bus with named topics between publishers and subscribers, so neither side knows the other.', lesson: 'pat-observer' },
  { term: 'Signal', def: 'A reactive value that tracks which computations read it, so dependents update automatically when it changes.', lesson: 'pat-observer' },
  { term: 'Decorator', def: 'A function that wraps another function with the same signature and adds behaviour, such as caching or timing.', lesson: 'pat-decorators-middleware' },
  { term: 'Middleware', def: 'Functions of (context, next) arranged as an onion: each runs code before and after the inner layers, or stops the chain.', lesson: 'pat-decorators-middleware' },
  { term: 'Proxy', def: 'An object that wraps another and intercepts reading, writing and deleting through traps.', lesson: 'pat-decorators-middleware' },
  { term: 'Chain of responsibility', def: 'A request goes along a list of handlers until the first suitable one takes it.', lesson: 'pat-decorators-middleware' },
  { term: 'Command', def: 'An action turned into an object with do and undo, so it can be stored, queued, undone and replayed.', lesson: 'pat-command-undo' },
  { term: 'Memento', def: 'Saving a complete snapshot of state so it can be restored later, as in undo history.', lesson: 'pat-command-undo' },
  { term: 'Adapter', def: 'A thin layer that translates an interface you do not control into the one your code expects.', lesson: 'pat-adapter-facade' },
  { term: 'Anti-corruption layer', def: 'A boundary where external data is converted and validated once, so foreign shapes never spread through your code.', lesson: 'pat-adapter-facade' },
  { term: 'Facade', def: 'One simple entry point that coordinates a multi-step subsystem, including undoing steps when something fails.', lesson: 'pat-adapter-facade' },
  { term: 'Repository', def: 'Domain-shaped methods over hidden storage, returning copies and enforcing rules such as unique keys.', lesson: 'pat-adapter-facade' },
  { term: 'Composite', def: 'Leaves and groups share one interface, so a single item and a whole tree are used the same way.', lesson: 'pat-composite-visitor' },
  { term: 'Specification', def: 'A wrapped predicate with and, or and not that return new specifications, so rules compose.', lesson: 'pat-composite-visitor' },
  { term: 'Visitor', def: 'Operations written as handler tables over a stable tree, so adding an operation never edits the node types.', lesson: 'pat-composite-visitor' },
  { term: 'Speculative generality', def: 'Building abstractions for needs that do not exist yet. Wait for the second real use case.', lesson: 'pat-capstone' },
  { term: 'XSS', def: 'Cross-site scripting: attacker-controlled text is interpreted by the browser as markup or code in your page, so it runs with your site\'s powers.', lesson: 'sec-xss' },
  { term: 'Output encoding', def: 'Converting data into inert text for the place it lands (HTML, attribute, URL, script, CSS) so it cannot be read as markup or code.', lesson: 'sec-xss' },
  { term: 'Allowlist', def: 'A short list of known-good values or fields that are accepted, with everything else refused. Safer than a blocklist of known-bad ones.', lesson: 'sec-xss' },
  { term: 'SQL injection', def: 'Data mixed into query text so it changes what the query means. Parameterized queries send text and values separately.', lesson: 'sec-injection' },
  { term: 'Path traversal', def: 'Using .. segments or absolute paths to reach files outside the intended folder. Resolve the path first, then check it is still inside.', lesson: 'sec-injection' },
  { term: 'Prototype pollution', def: 'Writing to Object.prototype through a key like __proto__ in an unsafe merge, which changes every object in the program.', lesson: 'sec-injection' },
  { term: 'Open redirect', def: 'A login or link that redirects to any address the user supplies, turning your domain into a phishing launcher.', lesson: 'sec-injection' },
  { term: 'Password hash', def: 'A deliberately slow, salted one-way function (Argon2, bcrypt, scrypt, PBKDF2) used to store passwords instead of the passwords themselves.', lesson: 'sec-auth' },
  { term: 'Salt', def: 'A random per-user value stored beside a password hash so identical passwords hash differently.', lesson: 'sec-auth' },
  { term: 'Constant-time comparison', def: 'Comparing secrets without stopping at the first difference, so timing reveals nothing about how much matched.', lesson: 'sec-auth' },
  { term: 'Session fixation', def: 'Planting a known session id before login. Rotating the id at login defeats it.', lesson: 'sec-auth' },
  { term: 'JWT', def: 'A signed token of three base64url parts: header, payload and signature. The payload is readable; the signature makes it tamper-evident.', lesson: 'sec-auth' },
  { term: 'Same-origin policy', def: 'The browser rule that scripts can read responses only from their own origin (scheme, host and port).', lesson: 'sec-cookies-cors-csrf' },
  { term: 'HttpOnly', def: 'A cookie flag that hides the cookie from JavaScript, limiting what an XSS bug can steal.', lesson: 'sec-cookies-cors-csrf' },
  { term: 'SameSite', def: 'A cookie attribute (Strict, Lax or None) controlling whether the cookie is sent on cross-site requests.', lesson: 'sec-cookies-cors-csrf' },
  { term: 'CSRF', def: 'Cross-site request forgery: another site makes the victim\'s browser send a request that carries their cookies. Defended with SameSite, tokens and Origin checks.', lesson: 'sec-cookies-cors-csrf' },
  { term: 'Preflight', def: 'The OPTIONS request a browser sends before a non-simple cross-origin request, asking the server for permission.', lesson: 'sec-cookies-cors-csrf' },
  { term: 'Content Security Policy', def: 'A response header listing where a page may load and run scripts, styles, images and more from, limiting the damage of injected code.', lesson: 'sec-headers-csp' },
  { term: 'Nonce', def: 'A random value created for each response, placed in the CSP header and on trusted script tags, so only those scripts run.', lesson: 'sec-headers-csp' },
  { term: 'HSTS', def: 'Strict-Transport-Security: tells browsers to use HTTPS only for a site for a period of time.', lesson: 'sec-headers-csp' },
  { term: 'Subresource Integrity', def: 'An integrity attribute holding a hash of a third-party file; the browser refuses to run it if the content differs.', lesson: 'sec-headers-csp' },
  { term: 'Mass assignment', def: 'Copying a whole request body into a record so a client can set fields such as role. Allowlist the fields instead.', lesson: 'sec-validation-uploads' },
  { term: 'Magic number', def: 'The first bytes of a file that identify its real type, regardless of its name or declared content type.', lesson: 'sec-validation-uploads' },
  { term: 'Token bucket', def: 'A rate limiter that holds tokens, refills them steadily and spends one per request, allowing bursts but a steady long-run rate.', lesson: 'sec-validation-uploads' },
  { term: 'Redaction', def: 'Replacing secrets in logs and error output with a placeholder, by field name and by pattern.', lesson: 'sec-validation-uploads' },
  { term: 'Lockfile', def: 'A file recording the exact dependency versions and integrity hashes installed, so installs are reproducible and verified.', lesson: 'sec-supply-chain-secrets' },
  { term: 'Typosquatting', def: 'Publishing a package whose name is a one-letter slip from a popular one, hoping to be installed by mistake.', lesson: 'sec-supply-chain-secrets' },
  { term: 'Semver range', def: 'A version constraint such as ^1.2.3 or ~1.2.3 describing which releases are acceptable.', lesson: 'sec-supply-chain-secrets' },
  { term: 'Entropy', def: 'A measure of how random a string looks, in bits per character. Real secrets have high entropy.', lesson: 'sec-supply-chain-secrets' },
  { term: 'STRIDE', def: 'A threat checklist: spoofing, tampering, repudiation, information disclosure, denial of service, elevation of privilege.', lesson: 'sec-capstone' },
  { term: 'IDOR', def: 'Insecure direct object reference: accepting an object id from a request without checking that this user may access that object.', lesson: 'sec-capstone' },
  { term: 'Deny by default', def: 'Granting no access until a rule explicitly allows it, so forgotten cases are refused rather than allowed.', lesson: 'sec-capstone' },
  { term: 'Defence in depth', def: 'Several independent layers of protection, so that one failure does not mean a breach.', lesson: 'sec-capstone' },
  { term: 'Provider', def: 'Any object the container can create and inject: a service, repository or value, registered under a token.', lesson: 'node-modules-di' },
  { term: 'Injection token', def: 'The key a provider is registered under and looked up by; a class, string or symbol.', lesson: 'node-modules-di' },
  { term: 'Provider scope', def: 'How long an instance lives: singleton (one shared), transient (new each time) or request (one per request).', lesson: 'node-modules-di' },
  { term: 'Module', def: 'A boundary that groups providers; only what it exports can be injected elsewhere, and it must import what it uses.', lesson: 'node-modules-di' },
  { term: 'Request lifecycle', def: 'The fixed order a request passes through: middleware, guards, interceptors, pipes, handler, with exception filters catching errors.', lesson: 'node-request-lifecycle' },
  { term: 'Guard', def: 'A yes/no check before the handler (authentication, roles, rate limits). A denial stops everything after it.', lesson: 'node-request-lifecycle' },
  { term: 'Interceptor', def: 'A wrapper around the handler call: code before and after, able to change the result, skip the call or recover from errors.', lesson: 'node-request-lifecycle' },
  { term: 'Pipe', def: 'A step that transforms and validates the handler\'s input (parse "42" to 42, reject bad values).', lesson: 'node-request-lifecycle' },
  { term: 'Exception filter', def: 'The one place that turns a thrown error into a response; unknown errors become a generic 500.', lesson: 'node-request-lifecycle' },
  { term: 'DTO', def: 'Data transfer object: the checked, typed shape accepted on the way in (or sent on the way out) at an API boundary.', lesson: 'node-dto-validation' },
  { term: 'Whitelisting', def: 'Keeping only fields you declared and dropping the rest, which stops mass assignment.', lesson: 'node-dto-validation' },
  { term: 'Serialization', def: 'Shaping what leaves the server per audience: exclude secrets, include fields by group, add computed ones.', lesson: 'node-dto-validation' },
  { term: 'Refresh token rotation', def: 'Each refresh token works once and returns a new pair; reuse of a spent token revokes the whole family.', lesson: 'node-auth-guards' },
  { term: 'Route metadata', def: 'Tags attached to handlers (public, roles, owner) that one generic guard reads to decide access.', lesson: 'node-auth-guards' },
  { term: '401 vs 403', def: '401: we do not know who you are. 403: we know, and the answer is no.', lesson: 'node-auth-guards' },
  { term: 'Idempotent', def: 'Doing it twice has the same effect as once. GET, PUT and DELETE are; POST is not, so retries need an idempotency key.', lesson: 'node-http-rest' },
  { term: 'Backpressure', def: 'Slowing a fast producer when its consumer cannot keep up, typically with a bounded queue whose push waits for room.', lesson: 'node-async-streams' },
  { term: 'Graceful shutdown', def: 'On a termination signal: stop accepting work, drain in-flight work, close resources in reverse order, then exit.', lesson: 'node-async-streams' },
  { term: 'N+1 query', def: 'One query for a list plus one per item. Fixed by batching the keys into a single query.', lesson: 'node-data-access' },
  { term: 'Savepoint', def: 'A named point inside a transaction that a nested step can roll back to without undoing the whole transaction.', lesson: 'node-data-access' },
  { term: 'Optimistic locking', def: 'Updating only if a version number is unchanged, so a stale write is detected as a conflict instead of overwriting.', lesson: 'node-data-access' },
  { term: 'Migration', def: 'A versioned, reversible schema change (up and down) applied in order and recorded only after it succeeds.', lesson: 'node-data-access' },
  { term: 'Fail fast', def: 'Validating configuration at startup and crashing with every problem listed, rather than failing on the first request.', lesson: 'node-capstone' },
  { term: 'Liveness vs readiness', def: 'Liveness: is the process alive (restart if not). Readiness: can it serve traffic now (stop routing if not).', lesson: 'node-capstone' },
  { term: 'Circuit breaker', def: 'Stops calling a failing dependency after N failures (open), then allows one trial (half-open) before closing again.', lesson: 'node-capstone' },
  { term: 'Composition root', def: 'The single place near the entry point where config, services and fakes are wired together.', lesson: 'node-capstone' },
  { term: 'CSR', def: 'Client-side rendering: the browser builds the page from JavaScript on every visit. Late first paint, cheap hosting.', lesson: 'rd-rendering-strategies' },
  { term: 'SSR', def: 'Server-side rendering: the server builds the HTML for each request. Early first paint, but server cost and a hydration step.', lesson: 'rd-rendering-strategies' },
  { term: 'SSG', def: 'Static site generation: pages are rendered once at build time and served as files from a CDN.', lesson: 'rd-rendering-strategies' },
  { term: 'ISR', def: 'Incremental static regeneration: static pages refreshed in the background after a time or on demand; stale-while-revalidate for whole pages.', lesson: 'rd-rendering-strategies' },
  { term: 'Hydration', def: 'Attaching JavaScript behavior to server-rendered HTML. Until it finishes the page looks ready but ignores clicks.', lesson: 'rd-hydration-streaming-rsc' },
  { term: 'Hydration mismatch', def: 'The first client render differs from the server HTML (dates, random ids, window checks), forcing React to warn or re-render.', lesson: 'rd-hydration-streaming-rsc' },
  { term: 'Streaming SSR', def: 'Sending the page shell at once and streaming each Suspense section as its data resolves, in completion order.', lesson: 'rd-hydration-streaming-rsc' },
  { term: 'Server Component', def: 'A component that runs only on the server, can await data directly and ships no JavaScript to the browser.', lesson: 'rd-hydration-streaming-rsc' },
  { term: 'Client boundary', def: 'A "use client" file: it and everything it imports are sent to the browser. Push it down to small interactive leaves.', lesson: 'rd-hydration-streaming-rsc' },
  { term: 'App Router', def: 'Next.js file-system routing: folders are URL segments; layout, loading, error and not-found files wrap the pages below.', lesson: 'rd-nextjs-essentials' },
  { term: 'Request memoization', def: 'Deduplicating identical fetches inside one render so components can fetch where they need data.', lesson: 'rd-nextjs-essentials' },
  { term: 'Data cache', def: 'A cache of fetch results across requests, expired by time (revalidate) or invalidated by tag.', lesson: 'rd-nextjs-essentials' },
  { term: 'Code splitting', def: 'Breaking the bundle into route, shared and common chunks so a page loads only the code it needs.', lesson: 'rd-bundles' },
  { term: 'Tree shaking', def: 'Removing unused exports from the bundle; it needs ES modules and provable absence of side effects.', lesson: 'rd-bundles' },
  { term: 'Barrel file', def: 'An index module that re-exports many modules; it can defeat tree shaking and drag in everything.', lesson: 'rd-bundles' },
  { term: 'Critical path', def: 'The longest chain of dependent requests (HTML, then CSS, then font) that delays first render.', lesson: 'rd-assets-critical-path' },
  { term: 'srcset and sizes', def: 'Attributes that offer several image widths and the slot width so the browser picks the smallest sufficient file.', lesson: 'rd-assets-critical-path' },
  { term: 'Preload and preconnect', def: 'Hints that fetch a late-discovered critical resource early, or open a third-party connection early.', lesson: 'rd-assets-critical-path' },
  { term: 's-maxage', def: 'A Cache-Control lifetime for shared caches (CDNs) that overrides max-age there.', lesson: 'rd-cdn-http-caching' },
  { term: 'Vary', def: 'A response header naming the request headers the response depends on; the cache keeps one copy per value.', lesson: 'rd-cdn-http-caching' },
  { term: 'Request coalescing', def: 'Sending one origin request for many simultaneous misses and sharing the cacheable result, avoiding a thundering herd.', lesson: 'rd-cdn-http-caching' },
  { term: 'Cache hit ratio', def: 'Hits divided by requests at the edge: the main number for how much traffic a CDN absorbs.', lesson: 'rd-cdn-http-caching' },
  { term: 'staleTime', def: 'How long cached query data counts as fresh and is returned without a request.', lesson: 'rd-client-data' },
  { term: 'Query key', def: 'The identity of cached server data, usually an array; equal keys share one entry and one in-flight request.', lesson: 'rd-client-data' },
  { term: 'Performance budget gate', def: 'A CI check comparing the median of several lab runs with a baseline, failing on regressions or missing metrics.', lesson: 'rd-capstone-performance-review' },
];
