/** Plain-English definitions. `lesson` is the lesson id where the idea is taught. */
export interface Term { term: string; def: string; lesson: string }

export const glossary: Term[] = [
  { term: 'Closure', def: 'A function that remembers the variables from where it was created, even after that place has finished running.', lesson: 'closures' },
  { term: 'Scope', def: 'The part of the code where a variable can be seen. Lookups start in the innermost scope and step outward.', lesson: 'closures' },
  { term: 'Lexical scope', def: 'Scope decided by where code is written, not where it runs.', lesson: 'closures' },
  { term: 'this', def: 'A value set each time a function is called, usually the object left of the dot. Arrow functions have no this of their own.', lesson: 'this-prototypes' },
  { term: 'Prototype', def: 'A hidden link from an object to another object that it borrows properties from when it does not have them itself.', lesson: 'this-prototypes' },
  { term: 'Constructor', def: 'A function used with new to create objects of one kind.', lesson: 'this-prototypes' },
  { term: 'Callback', def: 'A function you hand to someone else to call later.', lesson: 'promises' },
  { term: 'Promise', def: 'An object standing in for a value that is not ready yet. It is pending, then fulfilled or rejected, exactly once.', lesson: 'promises' },
  { term: 'Microtask', def: 'A small job (like a promise callback) that runs as soon as the current code ends, before the next timer.', lesson: 'event-loop' },
  { term: 'Event loop', def: 'The rule that picks what JavaScript runs next: one task, then all microtasks, then maybe a repaint.', lesson: 'event-loop' },
  { term: 'async / await', def: 'Syntax for writing promise code top to bottom. await pauses only that function until the promise settles.', lesson: 'async-await' },
  { term: 'AbortController', def: 'An object that lets you tell an operation (like a fetch) to stop, through its signal.', lesson: 'async-await' },
  { term: 'Debounce', def: 'Run a function only after the events have stopped for a while.', lesson: 'event-loop' },
  { term: 'Throttle', def: 'Run a function at most once per time window while events keep coming.', lesson: 'event-loop' },
  { term: 'Iterator', def: 'Something with a next() method that returns { value, done } until it is finished.', lesson: 'iterators' },
  { term: 'Generator', def: 'A function (function*) that can pause at each yield and resume later, producing values lazily.', lesson: 'iterators' },
  { term: 'Pure function', def: 'A function whose output depends only on its inputs and which has no side effects.', lesson: 'functional' },
  { term: 'Higher-order function', def: 'A function that takes or returns other functions.', lesson: 'functional' },
  { term: 'Currying', def: 'Turning f(a, b, c) into f(a)(b)(c): one argument per call.', lesson: 'functional' },
  { term: 'Immutability', def: 'Never changing data in place; build a new copy instead. React and memoised selectors rely on it.', lesson: 'objects' },
  { term: 'Shallow copy', def: 'A copy of the top level only; nested objects are still shared with the original.', lesson: 'objects' },
  { term: 'Reference', def: 'A link to an object. Copying a variable holding an object copies the link, not the object.', lesson: 'objects' },
  { term: 'Generic', def: 'A type with a slot (like T) that is filled in by whoever uses it.', lesson: 'ts-generics' },
  { term: 'Type narrowing', def: 'Checks in your code (typeof, ===, in) that turn a wide type into a more specific one inside a branch.', lesson: 'ts-generics' },
  { term: 'Conditional type', def: 'An if statement for types: A extends B ? X : Y.', lesson: 'ts-generics' },
  { term: 'Mapped type', def: 'A type that loops over the keys of another type to build a new one: { [K in keyof T]: … }.', lesson: 'ts-type-level' },
  { term: 'Template literal type', def: 'A type built from string pieces, which can also take strings apart with infer.', lesson: 'ts-type-level' },
  { term: 'Type predicate', def: 'A return type like x is string that promises the compiler what a true result means.', lesson: 'ts-real-world' },
  { term: 'JSX', def: 'Markup-like syntax that compiles to function calls returning React elements.', lesson: 'react-rendering' },
  { term: 'Props', def: 'The read-only inputs a component receives from its parent.', lesson: 'react-rendering' },
  { term: 'Key (React)', def: 'An identity for list items so React knows which item is which between renders.', lesson: 'react-rendering' },
  { term: 'State', def: 'Data a component remembers between renders; changing it makes React redraw.', lesson: 'react-state' },
  { term: 'Controlled input', def: 'A form field whose value lives in React state and flows back through onChange.', lesson: 'react-state' },
  { term: 'Lifting state up', def: 'Moving state to the closest common parent so siblings can share it.', lesson: 'react-state' },
  { term: 'Effect', def: 'Code that runs after rendering to sync with the outside world (timers, events, network).', lesson: 'react-effects' },
  { term: 'Cleanup', def: 'The function an effect returns; it undoes what the effect set up.', lesson: 'react-effects' },
  { term: 'Dependency array', def: 'The list of values an effect reads; React re-runs the effect when one changes.', lesson: 'react-effects' },
  { term: 'Stale closure', def: 'A function still using an old value from an earlier render.', lesson: 'react-effects' },
  { term: 'Custom hook', def: 'A function starting with use that calls other hooks, to reuse stateful logic.', lesson: 'react-hooks' },
  { term: 'Ref', def: 'A mutable box that survives renders and does not cause a render when changed.', lesson: 'react-hooks' },
  { term: 'Memoization', def: 'Remembering the result of a calculation so it is not repeated when the inputs are the same.', lesson: 'react-performance' },
  { term: 'Virtualisation', def: 'Rendering only the rows that are visible instead of all of them.', lesson: 'react-performance' },
  { term: 'Context', def: 'A way to share a value with many distant components without passing props through every level.', lesson: 'react-architecture' },
  { term: 'Reducer', def: 'A pure function (state, action) → next state, used to keep update rules in one place.', lesson: 'react-architecture' },
  { term: 'Error boundary', def: 'A component that catches rendering errors in its children and shows a fallback.', lesson: 'react-architecture' },
  { term: 'Compound component', def: 'A set of small components (Tabs, Tabs.List, …) that share state through context.', lesson: 'react-composition' },
  { term: 'ARIA', def: 'Attributes that describe roles and states of custom widgets to assistive technology.', lesson: 'react-composition' },
  { term: 'Roving tabindex', def: 'One item in a widget has tabindex 0 and arrow keys move it, so the widget is a single Tab stop.', lesson: 'react-composition' },
  { term: 'Coalescing', def: 'Keeping only the latest value per key so a fast feed produces far fewer updates.', lesson: 'prod-firehose' },
  { term: 'INP', def: 'Interaction to Next Paint: how long the page takes to respond after a tap or keypress.', lesson: 'prod-firehose' },
  { term: 'Cursor pagination', def: 'Loading the next page by saying "after this item" rather than "page 40", which is stable when data changes.', lesson: 'prod-large-data' },
  { term: 'Time slicing', def: 'Splitting a long job into short chunks with breaks so the page stays responsive.', lesson: 'prod-large-data' },
  { term: 'Backoff with jitter', def: 'Waiting longer after each failed retry, with a random amount so clients do not retry together.', lesson: 'prod-resilience' },
  { term: 'Half-open connection', def: 'A connection that has silently died without any close event.', lesson: 'prod-resilience' },
  { term: 'Sequence number', def: 'A counter on each message that lets a client spot duplicates, gaps and wrong order.', lesson: 'prod-resilience' },
  { term: 'Idempotency key', def: 'A unique id for one logical action so that repeating the request returns the original result.', lesson: 'prod-bet-placement' },
  { term: 'State machine', def: 'A model with explicit states and allowed transitions, so illegal moves are impossible.', lesson: 'prod-bet-placement' },
  { term: 'Memory leak', def: 'Memory that is still reachable but no longer needed, so it is never freed.', lesson: 'prod-memory' },
  { term: 'LRU cache', def: 'A cache that evicts the least recently used entry when it is full.', lesson: 'prod-memory' },
  { term: 'Web Worker', def: 'A separate thread for heavy JavaScript work, talked to with messages.', lesson: 'prod-workers' },
  { term: 'Structured clone', def: 'The algorithm that copies data when you postMessage it.', lesson: 'prod-workers' },
  { term: 'BroadcastChannel', def: 'A way for tabs of the same site to send messages to each other.', lesson: 'prod-multi-tab' },
  { term: 'Last-writer-wins', def: 'A conflict rule: the change with the highest version wins, so every tab converges.', lesson: 'prod-multi-tab' },
  { term: 'Leader election', def: 'Choosing one tab (for example the lowest alive id) to do a job once for everyone.', lesson: 'prod-multi-tab' },
  { term: 'Hash map', def: 'A structure that finds a value by its key in constant time on average (Map in JavaScript).', lesson: 'interview-ds' },
  { term: 'Trie', def: 'A tree with one node per character so words sharing a prefix share nodes.', lesson: 'interview-ds' },
  { term: 'Big-O', def: 'A way to describe how the cost of code grows with the size of its input.', lesson: 'interview-ds' },
  { term: 'Escaping', def: 'Converting special characters so text is treated as data, not as code, in HTML or URLs.', lesson: 'interview-frontend' },
  { term: 'Event bubbling', def: 'After an event hits its target, it travels back up through the parent elements, so a listener higher up can see it.', lesson: 'web-dom' },
  { term: 'Event capturing', def: 'The first half of an event\'s trip: from the document down to the target. Listeners opt in with { capture: true }.', lesson: 'web-dom' },
  { term: 'Event delegation', def: 'One listener on a parent that handles events from many children, using event.target.closest(selector) to find which child it was.', lesson: 'web-dom' },
  { term: 'Layout thrashing', def: 'Mixing DOM writes and layout reads in a loop so the browser has to recalculate layout again and again.', lesson: 'web-dom' },
  { term: 'IntersectionObserver', def: 'A browser API that tells you when an element enters or leaves the viewport, without scroll listeners.', lesson: 'web-dom' },
  { term: 'Compositing', def: 'The last rendering step: stacking painted layers on the GPU. transform and opacity changes only need this step.', lesson: 'web-dom' },
  { term: 'ETag', def: 'A fingerprint of a response. The browser sends it back in If-None-Match so the server can answer 304 Not Modified instead of re-sending the body.', lesson: 'web-network' },
  { term: 'Cache-Control', def: 'A response header that says how long and by whom a response may be reused (max-age, no-cache, no-store, immutable…).', lesson: 'web-network' },
  { term: 'Stale-while-revalidate', def: 'Serve the cached value immediately, even if it is a bit old, and refresh it once in the background.', lesson: 'web-network' },
  { term: 'CORS', def: 'The browser rule that stops a page reading responses from another origin unless that server opts in with Access-Control headers.', lesson: 'web-network' },
  { term: 'Preflight', def: 'An OPTIONS request the browser sends first to ask a cross-origin server whether the real request is allowed.', lesson: 'web-network' },
  { term: 'AbortController', def: 'An object whose signal you pass to fetch (and listeners); calling abort() cancels them.', lesson: 'web-network' },
  { term: 'Core Web Vitals', def: 'Google\'s three user-experience metrics: LCP (loading), INP (responsiveness) and CLS (visual stability).', lesson: 'web-perf' },
  { term: 'LCP', def: 'Largest Contentful Paint: when the biggest element in the viewport finished rendering. Good is 2.5 seconds or less.', lesson: 'web-perf' },
  { term: 'INP', def: 'Interaction to Next Paint: how long the slowest typical tap, click or key press takes to show a visible response. Good is 200 ms or less.', lesson: 'web-perf' },
  { term: 'CLS', def: 'Cumulative Layout Shift: a score for how much visible content jumped around unexpectedly. Good is 0.1 or less.', lesson: 'web-perf' },
  { term: 'Long task', def: 'A main-thread task over 50 ms. Anything the user does while it runs has to wait.', lesson: 'web-perf' },
  { term: 'Percentile', def: 'The value that a given share of samples are at or below. p75 means three out of four samples were this good or better.', lesson: 'web-perf' },
  { term: 'RUM', def: 'Real user monitoring: measuring performance in your actual users\' browsers instead of one test machine.', lesson: 'web-perf' },
  { term: 'Performance budget', def: 'A limit (for example, 170 KB of JavaScript) that a build or CI check enforces so pages do not creep heavier.', lesson: 'web-perf' },
  { term: 'Cursor pagination', def: 'Paging by pointing at the last item you saw instead of a page number, so inserted items do not cause repeats or gaps.', lesson: 'sys-design' },
  { term: 'Optimistic update', def: 'Showing the result of an action right away and rolling it back if the server says no.', lesson: 'sys-design' },
  { term: 'Debounce', def: 'Waiting for a pause in events (like typing) before acting, so a burst causes one action.', lesson: 'sys-design' },
  { term: 'Outbox', def: 'A local queue of things to send (such as chat messages) that retries until they succeed or are marked failed.', lesson: 'sys-design' },
  { term: 'Idempotency key', def: 'An id sent with a request so that repeating it is safe: the server treats the repeat as the same request.', lesson: 'sys-design' },
  { term: 'Big-O', def: 'A way to describe how the work grows as the input grows, ignoring constants: O(1) stays flat, O(n) grows in step, O(n²) grows with the square.', lesson: 'ds-arrays' },
  { term: 'Amortised cost', def: 'The average cost per operation over a long run: an occasional expensive step (like resizing an array) is paid for by many cheap ones.', lesson: 'ds-arrays' },
  { term: 'Binary search', def: 'Finding an item in sorted data by checking the middle and discarding the half that cannot contain it. O(log n).', lesson: 'ds-arrays' },
  { term: 'Hash function', def: 'A function that turns a key into a number, which a hash table reduces to a bucket index. The same key must always give the same number.', lesson: 'ds-hash-tables' },
  { term: 'Collision', def: 'Two different keys landing in the same bucket of a hash table. Chaining keeps a short list in each bucket.', lesson: 'ds-hash-tables' },
  { term: 'Load factor', def: 'Entries divided by buckets in a hash table. When it passes a limit (about 0.75) the table doubles its buckets and rehashes.', lesson: 'ds-hash-tables' },
  { term: 'Stack', def: 'A last-in, first-out collection: you add and remove at the top only. push and pop are O(1).', lesson: 'ds-stacks-queues' },
  { term: 'Queue', def: 'A first-in, first-out collection: add at the back, remove from the front.', lesson: 'ds-stacks-queues' },
  { term: 'Ring buffer', def: 'A fixed-size array whose read and write positions wrap around, so it remembers the last N items with no shifting.', lesson: 'ds-stacks-queues' },
  { term: 'Monotonic stack', def: 'A stack kept in sorted order by discarding items that can never be the answer, used for "next greater" style problems in O(n).', lesson: 'ds-stacks-queues' },
  { term: 'Linked list', def: 'Items stored in separate nodes that each point at the next one. Inserting or removing is O(1) once you hold the node; reaching item k is O(k).', lesson: 'ds-linked-lists' },
  { term: 'Sentinel node', def: 'A dummy node placed at the start (and sometimes end) of a list so the first and last real nodes need no special cases.', lesson: 'ds-linked-lists' },
  { term: 'Fast and slow pointers', def: 'Two pointers moving at different speeds along a list, used to find the middle or detect a cycle with O(1) memory.', lesson: 'ds-linked-lists' },
  { term: 'Binary search tree', def: 'A binary tree where everything in a node\'s left subtree is smaller and everything in its right subtree is larger, so search is O(height).', lesson: 'ds-trees' },
  { term: 'Tree traversal', def: 'Visiting every node: depth-first (pre-, in- or post-order) goes deep first; breadth-first (level-order) goes row by row with a queue.', lesson: 'ds-trees' },
  { term: 'Heap', def: 'A complete binary tree stored in an array where every parent is at most (min-heap) or at least (max-heap) its children. push and pop are O(log n).', lesson: 'ds-heaps' },
  { term: 'Priority queue', def: 'A collection that always hands you the most important item next. A heap is the usual implementation.', lesson: 'ds-heaps' },
  { term: 'Adjacency list', def: 'A graph stored as a map from each node to the list of its neighbours. Uses O(V + E) memory.', lesson: 'ds-graphs' },
  { term: 'Breadth-first search', def: 'Exploring a graph in rings of increasing distance using a queue; it finds shortest paths in unweighted graphs.', lesson: 'ds-graphs' },
  { term: 'Topological sort', def: 'An ordering of a directed acyclic graph where every edge points forward, such as a valid order for tasks with prerequisites.', lesson: 'ds-graphs' },
  { term: 'Dijkstra', def: 'Shortest paths in a graph with non-negative edge weights: always expand the closest unexplored node, using a min-heap.', lesson: 'ds-graphs' },
  { term: 'Union-find', def: 'A structure that tracks which items are connected as sets merge: find climbs to a set\'s root, union joins two roots. Nearly O(1) with path compression.', lesson: 'ds-specialist' },
  { term: 'Prefix sum', def: 'A running total stored so any range sum is one subtraction: sum(l..r) = prefix[r + 1] - prefix[l].', lesson: 'ds-specialist' },
  { term: 'Fenwick tree', def: 'A compact structure for prefix sums that also allows point updates, both in O(log n), using the lowest set bit of an index.', lesson: 'ds-specialist' },
];
