/** Plain-English definitions. `lesson` is the lesson id where the idea is taught. */
export interface Term { term: string; def: string; lesson: string }

export const glossary: Term[] = [
  { term: 'Closure', def: 'A function that remembers the variables from where it was created, even after that place has finished running.', lesson: 'closures' },
  { term: 'Scope', def: 'The part of the code where a variable can be seen. Lookups start in the innermost scope and step outward.', lesson: 'closures' },
  { term: 'Lexical scope', def: 'Scope decided by where code is written, not where it runs.', lesson: 'closures' },
  { term: 'this', def: 'A value set each time a function is called, usually the object left of the dot. Arrow functions have no this of their own.', lesson: 'this-prototypes' },
  { term: 'Prototype', def: 'A hidden link from an object to another object that it borrows properties from when it does not have them itself.', lesson: 'this-prototypes' },
  { term: 'Constructor', def: 'A function used with new to create objects of one kind.', lesson: 'this-prototypes' },
  { term: 'Callback', def: 'A function you hand to someone else to call later.', lesson: 'promises' },
  { term: 'Promise', def: 'An object standing in for a value that is not ready yet. It is pending, then fulfilled or rejected, exactly once.', lesson: 'promises' },
  { term: 'Microtask', def: 'A small job (like a promise callback) that runs as soon as the current code ends, before the next timer.', lesson: 'event-loop' },
  { term: 'Event loop', def: 'The rule that picks what JavaScript runs next: one task, then all microtasks, then maybe a repaint.', lesson: 'event-loop' },
  { term: 'async / await', def: 'Syntax for writing promise code top to bottom. await pauses only that function until the promise settles.', lesson: 'async-await' },
  { term: 'AbortController', def: 'An object that lets you tell an operation (like a fetch) to stop, through its signal.', lesson: 'async-await' },
  { term: 'Debounce', def: 'Run a function only after the events have stopped for a while.', lesson: 'event-loop' },
  { term: 'Throttle', def: 'Run a function at most once per time window while events keep coming.', lesson: 'event-loop' },
  { term: 'Iterator', def: 'Something with a next() method that returns { value, done } until it is finished.', lesson: 'iterators' },
  { term: 'Generator', def: 'A function (function*) that can pause at each yield and resume later, producing values lazily.', lesson: 'iterators' },
  { term: 'Pure function', def: 'A function whose output depends only on its inputs and which has no side effects.', lesson: 'functional' },
  { term: 'Higher-order function', def: 'A function that takes or returns other functions.', lesson: 'functional' },
  { term: 'Currying', def: 'Turning f(a, b, c) into f(a)(b)(c): one argument per call.', lesson: 'functional' },
  { term: 'Immutability', def: 'Never changing data in place; build a new copy instead. React and memoised selectors rely on it.', lesson: 'objects' },
  { term: 'Shallow copy', def: 'A copy of the top level only; nested objects are still shared with the original.', lesson: 'objects' },
  { term: 'Reference', def: 'A link to an object. Copying a variable holding an object copies the link, not the object.', lesson: 'objects' },
  { term: 'Generic', def: 'A type with a slot (like T) that is filled in by whoever uses it.', lesson: 'ts-generics' },
  { term: 'Type narrowing', def: 'Checks in your code (typeof, ===, in) that turn a wide type into a more specific one inside a branch.', lesson: 'ts-generics' },
  { term: 'Conditional type', def: 'An if statement for types: A extends B ? X : Y.', lesson: 'ts-generics' },
  { term: 'Mapped type', def: 'A type that loops over the keys of another type to build a new one: { [K in keyof T]: … }.', lesson: 'ts-type-level' },
  { term: 'Template literal type', def: 'A type built from string pieces, which can also take strings apart with infer.', lesson: 'ts-type-level' },
  { term: 'Type predicate', def: 'A return type like x is string that promises the compiler what a true result means.', lesson: 'ts-real-world' },
  { term: 'JSX', def: 'Markup-like syntax that compiles to function calls returning React elements.', lesson: 'react-rendering' },
  { term: 'Props', def: 'The read-only inputs a component receives from its parent.', lesson: 'react-rendering' },
  { term: 'Key (React)', def: 'An identity for list items so React knows which item is which between renders.', lesson: 'react-rendering' },
  { term: 'State', def: 'Data a component remembers between renders; changing it makes React redraw.', lesson: 'react-state' },
  { term: 'Controlled input', def: 'A form field whose value lives in React state and flows back through onChange.', lesson: 'react-state' },
  { term: 'Lifting state up', def: 'Moving state to the closest common parent so siblings can share it.', lesson: 'react-state' },
  { term: 'Effect', def: 'Code that runs after rendering to sync with the outside world (timers, events, network).', lesson: 'react-effects' },
  { term: 'Cleanup', def: 'The function an effect returns; it undoes what the effect set up.', lesson: 'react-effects' },
  { term: 'Dependency array', def: 'The list of values an effect reads; React re-runs the effect when one changes.', lesson: 'react-effects' },
  { term: 'Stale closure', def: 'A function still using an old value from an earlier render.', lesson: 'react-effects' },
  { term: 'Custom hook', def: 'A function starting with use that calls other hooks, to reuse stateful logic.', lesson: 'react-hooks' },
  { term: 'Ref', def: 'A mutable box that survives renders and does not cause a render when changed.', lesson: 'react-hooks' },
  { term: 'Memoization', def: 'Remembering the result of a calculation so it is not repeated when the inputs are the same.', lesson: 'react-performance' },
  { term: 'Virtualisation', def: 'Rendering only the rows that are visible instead of all of them.', lesson: 'react-performance' },
  { term: 'Context', def: 'A way to share a value with many distant components without passing props through every level.', lesson: 'react-architecture' },
  { term: 'Reducer', def: 'A pure function (state, action) → next state, used to keep update rules in one place.', lesson: 'react-architecture' },
  { term: 'Error boundary', def: 'A component that catches rendering errors in its children and shows a fallback.', lesson: 'react-architecture' },
  { term: 'Compound component', def: 'A set of small components (Tabs, Tabs.List, …) that share state through context.', lesson: 'react-composition' },
  { term: 'ARIA', def: 'Attributes that describe roles and states of custom widgets to assistive technology.', lesson: 'react-composition' },
  { term: 'Roving tabindex', def: 'One item in a widget has tabindex 0 and arrow keys move it, so the widget is a single Tab stop.', lesson: 'react-composition' },
  { term: 'Coalescing', def: 'Keeping only the latest value per key so a fast feed produces far fewer updates.', lesson: 'prod-firehose' },
  { term: 'INP', def: 'Interaction to Next Paint: how long the page takes to respond after a tap or keypress.', lesson: 'prod-firehose' },
  { term: 'Cursor pagination', def: 'Loading the next page by saying "after this item" rather than "page 40", which is stable when data changes.', lesson: 'prod-large-data' },
  { term: 'Time slicing', def: 'Splitting a long job into short chunks with breaks so the page stays responsive.', lesson: 'prod-large-data' },
  { term: 'Backoff with jitter', def: 'Waiting longer after each failed retry, with a random amount so clients do not retry together.', lesson: 'prod-resilience' },
  { term: 'Half-open connection', def: 'A connection that has silently died without any close event.', lesson: 'prod-resilience' },
  { term: 'Sequence number', def: 'A counter on each message that lets a client spot duplicates, gaps and wrong order.', lesson: 'prod-resilience' },
  { term: 'Idempotency key', def: 'A unique id for one logical action so that repeating the request returns the original result.', lesson: 'prod-bet-placement' },
  { term: 'State machine', def: 'A model with explicit states and allowed transitions, so illegal moves are impossible.', lesson: 'prod-bet-placement' },
  { term: 'Memory leak', def: 'Memory that is still reachable but no longer needed, so it is never freed.', lesson: 'prod-memory' },
  { term: 'LRU cache', def: 'A cache that evicts the least recently used entry when it is full.', lesson: 'prod-memory' },
  { term: 'Web Worker', def: 'A separate thread for heavy JavaScript work, talked to with messages.', lesson: 'prod-workers' },
  { term: 'Structured clone', def: 'The algorithm that copies data when you postMessage it.', lesson: 'prod-workers' },
  { term: 'BroadcastChannel', def: 'A way for tabs of the same site to send messages to each other.', lesson: 'prod-multi-tab' },
  { term: 'Last-writer-wins', def: 'A conflict rule: the change with the highest version wins, so every tab converges.', lesson: 'prod-multi-tab' },
  { term: 'Leader election', def: 'Choosing one tab (for example the lowest alive id) to do a job once for everyone.', lesson: 'prod-multi-tab' },
  { term: 'Hash map', def: 'A structure that finds a value by its key in constant time on average (Map in JavaScript).', lesson: 'interview-ds' },
  { term: 'Trie', def: 'A tree with one node per character so words sharing a prefix share nodes.', lesson: 'interview-ds' },
  { term: 'Big-O', def: 'A way to describe how the cost of code grows with the size of its input.', lesson: 'interview-ds' },
  { term: 'Escaping', def: 'Converting special characters so text is treated as data, not as code, in HTML or URLs.', lesson: 'interview-frontend' },
];
